{{- with index .Values "secrets" "egov-location" }}
apiVersion: v1
kind: Secret
metadata:
  # Adding default values for 'name' and 'namespace' is good practice,
  # in case they are not explicitly provided in 'secrets.egov-location'.
  name: {{ .name | default "egov-location-secret" }}
  namespace: {{ .namespace | default "default" }}
type: Opaque
data:
  # Applying | default "" to ensure b64enc always receives a string
  gmapskey: {{ .gmapskey | default "" | b64enc | quote }}
{{- end }}
