#checking helmfile
helmfiles:
  # - path: ./charts/backbone-services/backboneservices-helmfile.yaml
  - path: ./charts/backbone-services/backboneservices-helmfile.yaml.gotmpl
  - path: ./charts/core-services/coreservices-helmfile.yaml.gotmpl
