#checking helmfile

environments:
  uat:
    values:
      - ./charts/environments/env-secrets.yaml
      - ./charts/environments/env.yaml

---

helmfiles:
  - path: ./charts/backbone-services/backboneservices-helmfile.yaml.gotmpl
  - path: ./charts/core-services/coreservices-helmfile.yaml.gotmpl
  - path: ./charts/urban/urban-helmfile.yaml.gotmpl
  - path: ./charts/common-services/common-services-helmfile.yaml.gotmpl
  - path: ./charts/analytics/analytics-helmfile.yaml.gotmpl
#  - path: ./charts/sanitation/sanitation-helmfile.yaml.gotmpl
  - path: ./charts/auxiliary-services/auxiliary-helmfile.yaml.gotmpl
  - path: ./charts/monitoring/monitoring-helmfile.yaml.gotmpl
