apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{"kubernetes.io/enforce-mountable-secrets":"true"},"name":"gateway-service-account","namespace":"egov"}}
    kubernetes.io/enforce-mountable-secrets: "true"
  creationTimestamp: "2025-07-17T00:49:16Z"
  name: gateway-service-account
  namespace: egov
  resourceVersion: "52363"
  uid: 3f591181-2294-4d6a-9615-5c84ee5090cc
secrets: # <--- ADD THIS LINE
- name: digitltsdbdsn # <--- ADD THIS LINE (make sure 'db' is the correct name of your database secret)