apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{"kubernetes.io/enforce-mountable-secrets":"true"},"name":"gateway-service-account","namespace":"egov"}}
    kubernetes.io/enforce-mountable-secrets: "true"
  name: gateway-service-account
  namespace: egov
secrets: # <--- ADD THIS LINE
- name: db # Updated to match Role's resourceNames