# filename: secret-reader-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader-role
  namespace: egov # Must be in the same namespace as the secret and service account
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get"] # Allows reading specific secrets
  resourceNames: ["db"] # Specifically grants access to the "db" secret
