{{- $serviceName := .Values.name | default "unknown" -}}
{{- if eq $serviceName "configmaps" }}
{{- if .Values.secrets }}
{{- range $secretName, $secretData := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Values.namespace | default "egov" }}
type: Opaque
data:
{{- range $key, $value := $secretData }}
  {{- if not (kindIs "map" $value) }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}