apiVersion: v1
preferences: {}
kind: Config
clusters:
- cluster:
    server: https://0BC72E1672A6DBA30B4AC75A68194734.gr7.ap-south-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJU0MrbWJSUHVITFF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01UUXhOREV5TkRWYUZ3MHpOVEEzTVRJeE5ERTNORFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMyMTBzMUdGR2dxdzhEVjQrUEw2dkQxUzlYTnVaODJwUDFXM3FyTnZKT2FOd2gwK2piSk51bHY2eEsKNGZLYTl2MndFUjIveVh6QVA4UEc3aGxMMVNZajZ3QlRpRVpESDBkRjhBZFk5c3V3YjBSZ0g1VEVSM1lubFZxMAoxNGFJTTN2MzVVK1Y1WEdTcmZDU3FyMmgxWXcreVZtYWExTkpzUUYza1h6V05Tcm41UjIwSjlTUGs2d2RrY0tqCktyRnUxRGN2MjRxV05qL0QwYTlBeC9Pajc1cTZNRHVSVEgwUGlxQUx1MHo0cDg3V3N1Mm0vY25CWkErRGh5aDAKSmJ2aWZkcEtXVGJrY3B0dUhIT3pNSDYwcmRNamtoSHN0ZGNaTUlJM3hPamhtNkoyVXR5dWtwZlpMdXg1RHh3YwpNT094MmlzNEdCVkdQcHlKVWl4ZUJSaCtNQVExQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSRXhwUHpKdHQwWDhVM0xJV0hoM3g0emlWK1d6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVdQZ1FZYlV5OAprTFFTS3ArY2R4MjgvRE5yc2MxNzNWakgvb1MyK3VFcHk1bmlPT3Z0MVFXQU1ZRjhQOHB2bk14dXFMZDd2OWVBCmo5UjN3TTNtVlNqaXpIU2ZCeFJSZ1M5cmREMy9JL2hUbUc4K1VDcndYd2pjSzRhV1hoLzlqYXk4ZHdZNVNxRzkKSEljMTdMUFc4aTBrV0RuSXJrZ0xQQzQweFhFR0kyVzdoYnNoVVhMemtaRGRaZExxQ1gvS0xkUXJDSCsyaFRjRQo5NGpLcjJkNGp3N0ZNRy9OZnJIMStSRXFTSmpycG8zaUxvUENqYUsxYnc4MGQvaGpyTCtXT3VBNTJPQm5DSTR3CkFibnF6dFg4VEl3YnJ1RHpDS3pUTzArU2Y2WFRmU0M3NWpIQkQ3SituUGpiaDFmdWlHQ3luQ3NpSjE3OHhMK1AKbndxZUQ5amhGWDFpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  name: eks_digit-lts-dsn
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJU0MrbWJSUHVITFF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01UUXhOREV5TkRWYUZ3MHpOVEEzTVRJeE5ERTNORFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMyMTBzMUdGR2dxdzhEVjQrUEw2dkQxUzlYTnVaODJwUDFXM3FyTnZKT2FOd2gwK2piSk51bHY2eEsKNGZLYTl2MndFUjIveVh6QVA4UEc3aGxMMVNZajZ3QlRpRVpESDBkRjhBZFk5c3V3YjBSZ0g1VEVSM1lubFZxMAoxNGFJTTN2MzVVK1Y1WEdTcmZDU3FyMmgxWXcreVZtYWExTkpzUUYza1h6V05Tcm41UjIwSjlTUGs2d2RrY0tqCktyRnUxRGN2MjRxV05qL0QwYTlBeC9Pajc1cTZNRHVSVEgwUGlxQUx1MHo0cDg3V3N1Mm0vY25CWkErRGh5aDAKSmJ2aWZkcEtXVGJrY3B0dUhIT3pNSDYwcmRNamtoSHN0ZGNaTUlJM3hPamhtNkoyVXR5dWtwZlpMdXg1RHh3YwpNT094MmlzNEdCVkdQcHlKVWl4ZUJSaCtNQVExQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSRXhwUHpKdHQwWDhVM0xJV0hoM3g0emlWK1d6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVdQZ1FZYlV5OAprTFFTS3ArY2R4MjgvRE5yc2MxNzNWakgvb1MyK3VFcHk1bmlPT3Z0MVFXQU1ZRjhQOHB2bk14dXFMZDd2OWVBCmo5UjN3TTNtVlNqaXpIU2ZCeFJSZ1M5cmREMy9JL2hUbUc4K1VDcndYd2pjSzRhV1hoLzlqYXk4ZHdZNVNxRzkKSEljMTdMUFc4aTBrV0RuSXJrZ0xQQzQweFhFR0kyVzdoYnNoVVhMemtaRGRaZExxQ1gvS0xkUXJDSCsyaFRjRQo5NGpLcjJkNGp3N0ZNRy9OZnJIMStSRXFTSmpycG8zaUxvUENqYUsxYnc4MGQvaGpyTCtXT3VBNTJPQm5DSTR3CkFibnF6dFg4VEl3YnJ1RHpDS3pUTzArU2Y2WFRmU0M3NWpIQkQ3SituUGpiaDFmdWlHQ3luQ3NpSjE3OHhMK1AKbndxZUQ5amhGWDFpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0BC72E1672A6DBA30B4AC75A68194734.gr7.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:331029743701:cluster/digit-lts-dsn
contexts:
- context:
    cluster: eks_digit-lts-dsn
    user: eks_digit-lts-dsn
  name: eks_digit-lts-dsn
- context:
    cluster: arn:aws:eks:ap-south-1:331029743701:cluster/digit-lts-dsn
    user: arn:aws:eks:ap-south-1:331029743701:cluster/digit-lts-dsn
  name: arn:aws:eks:ap-south-1:331029743701:cluster/digit-lts-dsn
current-context: arn:aws:eks:ap-south-1:331029743701:cluster/digit-lts-dsn
users:
- name: eks_digit-lts-dsn
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: aws-iam-authenticator
      args:
      - token
      - -i
      - digit-lts-dsn
- name: arn:aws:eks:ap-south-1:331029743701:cluster/digit-lts-dsn
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - digit-lts-dsn
      - --output
      - json
      command: aws
